code --install-extension astro-build.astro-vscode
code --install-extension bierner.markdown-preview-github-styles
code --install-extension brunnerh.insert-unicode
code --install-extension Cardinal90.multi-cursor-case-preserve
code --install-extension esbenp.prettier-vscode
code --install-extension hoovercj.vscode-power-mode
code --install-extension iliazeus.vscode-ansi
code --install-extension leonardssh.vscord
code --install-extension mechatroner.rainbow-csv
code --install-extension meganrogge.template-string-converter
code --install-extension ms-python.python
code --install-extension ms-vscode.hexeditor
code --install-extension ms-vscode.wordcount
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension PKief.material-icon-theme
code --install-extension s-nlf-fh.glassit
code --install-extension usernamehw.errorlens
code --install-extension vue.volar
code --install-extension wix.vscode-import-cost
